/*
 * ZTP API SERVER
 * APIs for ZTP-API-SERVER project
 *
 * OpenAPI spec version: 1.0.0
 * Contact: ztp@zalopay.vn
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.phucch.auth;


import com.phucch.builder.Pair;

import java.util.List;
import java.util.Map;

public interface Authentication {
    /**
     * Apply authentication settings to header and query params.
     *
     * @param queryParams List of query parameters
     * @param headerParams Map of header parameters
     */
    void applyToParams(List<Pair> queryParams, Map<String, String> headerParams);
}
