/*
 * ZTP API SERVER
 * APIs for ZTP-API-SERVER project
 *
 * OpenAPI spec version: 1.0.0
 * Contact: ztp@zalopay.vn
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.phucch.auth;

public enum OAuthFlow {
    accessCode, implicit, password, application
}
